from __future__ import annotations

EXPECTED_PUBLIC_NAMES = (
    "discover",
    "get_capability",
    "invoke",
    "generate",
    "render",
    "renderer_main",
    "support",
    "RenderContext",
    "Capability",
    "DiscoveryResult",
    "EventStreamRecord",
    "InvocationResult",
    "AstridSDKError",
    "CapabilityNotFoundError",
    "CapabilityAmbiguousError",
    "CapabilityValidationError",
    "CapabilityMissingInputError",
    "CapabilityPreconditionError",
    "CapabilityRuntimeError",
    "CapabilityLeaseError",
    "CapabilityEventLogError",
    "UnsupportedCapabilityError",
    "CapabilityInvocationError",
    "CapabilityHandle",
    "Port",
    "Output",
    "AliasRecord",
    "Provenance",
    "SafetyDeclaration",
    "ExecError",
)

HEAVY_MODULES = (
    "astrid.sdk",
    "astrid.core.execution.executor.registry",
    "astrid.core.execution.executor.runner",
    "astrid.core.execution.orchestrator.registry",
    "astrid.core.execution.orchestrator.runner",
)
