"""Backend adapter abstract interface and shared result type.

SD-004: Backend dispatch goes through :class:`BackendAdapter`.  Every
backend (local vibecomfy, cloud fal, future runpod, etc.) implements
this single-method interface so the executor stays thin.
"""

from __future__ import annotations

import time
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any


@dataclass
class GenerationResult:
    """Normalised result from a single backend generation call.

    Every adapter returns this same shape regardless of whether it talked
    to a local ComfyUI process or a remote HTTP API.
    """

    #: Absolute paths to generated output media files (image or video), one per ``count``.
    image_paths: list[Path] = field(default_factory=list)

    @property
    def video_paths(self) -> list[Path]:
        """Read-only alias for :attr:`image_paths` — identical object reference.

        When generating video the output paths still live in ``image_paths``
        (the dataclass makes no distinction between modalities).  This property
        lets callers use the semantically clearer ``result.video_paths`` without
        breaking existing image-only code that reads ``result.image_paths``.
        """
        return self.image_paths

    #: The actual seed that was used (resolved from caller input or
    #: generated by the backend).
    seed_used: int = 0

    #: Identity of the model that actually ran — the vibecomfy template
    #: id or the fal endpoint slug (e.g. ``"image/z_image"``,
    #: ``"fal-ai/flux/dev"``).
    model_actual: str = ""

    #: Estimated cost in USD, if the backend reported one.  ``None`` for
    #: local backends or when cost data is unavailable.
    cost_usd: float | None = None

    #: Wall-clock duration of the generation call in milliseconds.
    duration_ms: int = 0

    #: Features the caller supplied that this (model, mode, backend) cell
    #: honoured.
    applied_features: list[str] = field(default_factory=list)

    #: Features the caller supplied that this cell does *not* support —
    #: dropped with a warning.
    dropped_features: list[str] = field(default_factory=list)

    #: Optional request identifier returned by the cloud provider
    #: (e.g. fal ``request_id``).
    request_id: str | None = None

    #: Optional list of source URLs for the generated assets (cloud
    #: providers often return temporary download URLs before the adapter
    #: fetches them).
    source_urls: list[str] | None = None


class BackendAdapter(ABC):
    """Abstract interface for generation backends.

    Every backend (local vibecomfy, cloud fal, etc.) implements exactly
    one method: :meth:`generate`.  The executor receives the resolved
    (model, mode, backend) triple and dispatches to the appropriate
    adapter without any backend-specific branching.
    """

    @abstractmethod
    def generate(
        self,
        entry: Any,  # ModelEntry (lazy-imported to avoid circular deps)
        mode: str,
        params: dict[str, Any],
        out_dir: Path,
    ) -> GenerationResult:
        """Run generation for one *(entry, mode)* pair.

        Args:
            entry: The resolved :class:`~astrid.core.model_catalog.schema.ModelEntry`.
            mode: Canonical mode name (``"t2i"``, ``"i2i"``, ``"edit"``, …).
            params: Feature values keyed by canonical feature name
                (``"prompt"``, ``"seed"``, ``"image_ref"``, …).  Already
                validated against the mode's ``supports`` / ``requires``.
            out_dir: Directory where output images should be written.

        Returns:
            A :class:`GenerationResult` with output paths, metadata, and
            cost/duration information.
        """
        ...
