"""Backend adapter abstract interface and shared result type.

SD-004: Backend dispatch goes through :class:`BackendAdapter`.  Every
backend (local vibecomfy, cloud fal, future runpod, etc.) implements
this single-method interface so the executor stays thin.
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Iterable

from astrid.contracts.exec_error import ExecError


def parse_dimension_pair(
    value: str, *, allow_single: bool = False
) -> tuple[int, int] | None:
    """Parse ``WxH`` style strings into ``(width, height)``."""

    if not value or not isinstance(value, str):
        return None
    value = value.strip()
    if not value:
        return None
    for sep in ("x", "X", "*", ","):
        if sep in value:
            parts = value.split(sep)
            if len(parts) == 2:
                try:
                    return int(parts[0].strip()), int(parts[1].strip())
                except (ValueError, TypeError):
                    pass
            return None
    if allow_single:
        try:
            dim = int(value)
            return dim, dim
        except (ValueError, TypeError):
            return None
    return None


def derive_frames_from_duration(params: dict[str, Any]) -> int | None:
    """Fill ``params['frames']`` from duration and fps when possible."""

    if (
        params.get("duration") is None
        or params.get("frames") is not None
        or params.get("fps") is None
    ):
        return None
    try:
        duration_s = float(params["duration"])
        fps_val = float(params["fps"])
        params["frames"] = round(duration_s * fps_val)
        return int(params["frames"])
    except (ValueError, TypeError):
        return None


def split_feature_support(
    params: dict[str, Any], supported: Iterable[str]
) -> tuple[list[str], list[str]]:
    """Return sorted ``(applied, dropped)`` feature names for non-None params."""

    supported_set = set(supported)
    supplied_features = {key for key, value in params.items() if value is not None}
    return sorted(supplied_features & supported_set), sorted(
        supplied_features - supported_set
    )


@dataclass
class GenerationResult:
    """Normalised result from a single backend generation call.

    Every adapter returns this same shape regardless of whether it talked
    to a local ComfyUI process or a remote HTTP API.

    The dataclass is intentionally *not* frozen — executors and adapters
    enrich fields (``manifest``, ``run_dir``) after the adapter returns,
    and the facade may update ``run_dir`` to reflect project routing.
    """

    #: Absolute paths to generated output media files (image or video), one per ``count``.
    image_paths: list[Path] = field(default_factory=list)

    @property
    def video_paths(self) -> list[Path]:
        """Read-only alias for :attr:`image_paths` — identical object reference.

        When generating video the output paths still live in ``image_paths``
        (the dataclass makes no distinction between modalities).  This property
        lets callers use the semantically clearer ``result.video_paths`` without
        breaking existing image-only code that reads ``result.image_paths``.
        """
        return self.image_paths

    @property
    def path(self) -> Path | None:
        """First output media path, or ``None`` when no outputs were produced.

        Convenience accessor so callers can write ``result.path`` instead of
        ``result.image_paths[0]`` (with the same semantics regardless of
        whether the result carries images or video).
        """
        return self.image_paths[0] if self.image_paths else None

    #: The actual seed that was used (resolved from caller input or
    #: generated by the backend).
    seed_used: int = 0

    #: Identity of the model that actually ran — the vibecomfy template
    #: id or the fal endpoint slug (e.g. ``"image/z_image"``,
    #: ``"fal-ai/flux/dev"``).
    model_actual: str = ""

    #: Estimated cost in USD, if the backend reported one.  ``None`` for
    #: local backends or when cost data is unavailable.
    cost_usd: float | None = None

    #: Wall-clock duration of the generation call in milliseconds.
    duration_ms: int = 0

    #: Features the caller supplied that this (model, mode, backend) cell
    #: honoured.
    applied_features: list[str] = field(default_factory=list)

    #: Features the caller supplied that this cell does *not* support —
    #: dropped with a warning.
    dropped_features: list[str] = field(default_factory=list)

    #: Optional request identifier returned by the cloud provider
    #: (e.g. fal ``request_id``).
    request_id: str | None = None

    #: Optional list of source URLs for the generated assets (cloud
    #: providers often return temporary download URLs before the adapter
    #: fetches them).
    source_urls: list[str] | None = None

    #: Structured failure, if the generation did not succeed.  ``ok`` is
    #: derived from this being ``None`` — adapters populate it instead of
    #: signalling failure out of band.
    error: ExecError | None = None

    #: Full canonical manifest dict (schema v2), populated by the executor
    #: after the adapter returns.  ``None`` until enriched.
    manifest: dict[str, Any] | None = None

    #: Canonical project run directory where outputs landed.  Set by the
    #: executor (or the facade during project routing) after generation.
    #: ``None`` when the output directory is not known or not project-backed.
    run_dir: Path | None = None

    @property
    def ok(self) -> bool:
        """A generation succeeded exactly when it carries no :class:`ExecError`."""
        return self.error is None

    # ------------------------------------------------------------------
    # Serialization helpers
    # ------------------------------------------------------------------

    def to_dict(self) -> dict[str, Any]:
        """Return a JSON-safe dict representation of this result.

        All :class:`Path` values are converted to strings so the dict can
        be serialised with :func:`json.dumps` without a custom encoder.
        The ``error`` field is serialised via :func:`dataclasses.asdict`
        when present.

        Round-tripping is supported via :meth:`from_dict`.
        """
        result: dict[str, Any] = {
            "image_paths": [str(p) for p in self.image_paths],
            "seed_used": self.seed_used,
            "model_actual": self.model_actual,
            "cost_usd": self.cost_usd,
            "duration_ms": self.duration_ms,
            "applied_features": list(self.applied_features),
            "dropped_features": list(self.dropped_features),
            "request_id": self.request_id,
            "source_urls": (
                list(self.source_urls) if self.source_urls is not None else None
            ),
            "error": _exec_error_to_json_safe(self.error),
            "manifest": self.manifest,
            "run_dir": str(self.run_dir) if self.run_dir is not None else None,
        }
        return result

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "GenerationResult":
        """Reconstruct a :class:`GenerationResult` from a :meth:`to_dict` payload.

        String paths in ``image_paths`` and ``run_dir`` are converted back
        to :class:`Path` objects.  The ``error`` field is reconstructed as
        an :class:`ExecError` when the dict carries the expected keys.
        """
        image_paths = [Path(p) for p in data.get("image_paths", [])]
        run_dir_raw = data.get("run_dir")
        run_dir = Path(run_dir_raw) if run_dir_raw else None

        error_raw = data.get("error")
        error: ExecError | None = None
        if isinstance(error_raw, dict) and "code" in error_raw:
            error = ExecError(
                code=error_raw.get("code", ""),
                type=error_raw.get("type", ""),
                message=error_raw.get("message", ""),
                recovery=error_raw.get("recovery", ""),
            )

        return cls(
            image_paths=image_paths,
            seed_used=data.get("seed_used", 0),
            model_actual=data.get("model_actual", ""),
            cost_usd=data.get("cost_usd"),
            duration_ms=data.get("duration_ms", 0),
            applied_features=list(data.get("applied_features", [])),
            dropped_features=list(data.get("dropped_features", [])),
            request_id=data.get("request_id"),
            source_urls=(
                list(data["source_urls"])
                if data.get("source_urls") is not None
                else None
            ),
            error=error,
            manifest=data.get("manifest"),
            run_dir=run_dir,
        )


def _exec_error_to_json_safe(error: ExecError | None) -> dict[str, Any] | None:
    """Convert an :class:`ExecError` to a plain dict suitable for JSON."""
    if error is None:
        return None
    return {
        "code": error.code,
        "type": error.type,
        "message": error.message,
        "recovery": getattr(error, "recovery", ""),
    }


class BackendAdapter(ABC):
    """Abstract interface for generation backends.

    Every backend (local vibecomfy, cloud fal, etc.) implements exactly
    one method: :meth:`generate`.  The executor receives the resolved
    (model, mode, backend) triple and dispatches to the appropriate
    adapter without any backend-specific branching.
    """

    @abstractmethod
    def generate(
        self,
        entry: Any,  # ModelEntry (lazy-imported to avoid circular deps)
        mode: str,
        params: dict[str, Any],
        out_dir: Path,
    ) -> GenerationResult:
        """Run generation for one *(entry, mode)* pair.

        Args:
            entry: The resolved :class:`~astrid.core.model_catalog.schema.ModelEntry`.
            mode: Canonical mode name (``"t2i"``, ``"i2i"``, ``"edit"``, …).
            params: Feature values keyed by canonical feature name
                (``"prompt"``, ``"seed"``, ``"image_ref"``, …).  Already
                validated against the mode's ``supports`` / ``requires``.
            out_dir: Directory where output images should be written.

        Returns:
            A :class:`GenerationResult` with output paths, metadata, and
            cost/duration information.
        """
        ...
