#!/usr/bin/env python3
"""Render preset: "wink turn" — a rigged character seen from behind.

The figure stands with its back to the camera (arms by its sides), then turns
only its **head** to look back toward the camera (like someone called its name),
gives a quick **wink** (via an eye-blink shape key), while the camera
**dollies in** to a head close-up.

This is a *scratchpad render* — it lives outside the core engine and leverages
``astrid.packs.blender.render_core`` only for settings normalization. Adding a
new render means dropping another module in this package with a ``build()``
function; see ``README.md``.

``build(settings)`` returns a self-contained Blender Python script. The script
reads the mesh path and output directory from the ``__MESH_FILE__`` and
``__OUTPUT__`` placeholders, which the render runner (server or local executor)
fills with the resolved paths before invoking Blender.
"""

from __future__ import annotations

from typing import Any

from astrid.packs.blender.render_core import normalize_settings


_TEMPLATE = '''\
"""Auto-generated by astrid.packs.blender.renders.wink_turn."""
import bpy
import math
import os
from mathutils import Vector, Matrix

SETTINGS = __SETTINGS__
OUTPUT = __OUTPUT__
MESH_FILE = __MESH_FILE__
TARGET_HEIGHT = 2.0


def build():
    bpy.ops.wm.read_factory_settings(use_empty=True)
    sce = bpy.context.scene

    ext = MESH_FILE.lower().rsplit(".", 1)[-1] if MESH_FILE else ""
    if ext in ("gltf", "glb"):
        bpy.ops.import_scene.gltf(filepath=MESH_FILE)
    elif ext == "fbx":
        bpy.ops.import_scene.fbx(filepath=MESH_FILE)
    else:
        raise RuntimeError("unsupported mesh format: " + str(MESH_FILE))

    bpy.context.view_layer.update()
    meshes = [o for o in bpy.data.objects if o.type == "MESH"]
    if not meshes:
        raise RuntimeError("no mesh objects imported from " + str(MESH_FILE))

    # --- normalize: scale to TARGET_HEIGHT, center at origin, feet on ground ---
    try:
        coords = []
        for m in meshes:
            for corner in m.bound_box:
                coords.append(m.matrix_world @ Vector(corner))
        xs = [c.x for c in coords]; ys = [c.y for c in coords]; zs = [c.z for c in coords]
        minx, maxx = min(xs), max(xs); miny, maxy = min(ys), max(ys); minz, maxz = min(zs), max(zs)
        h = (maxz - minz) or 1.0
        s = TARGET_HEIGHT / h
        c = Vector(((minx + maxx) / 2, (miny + maxy) / 2, minz))
        bpy.ops.object.empty_add(location=c)
        pivot = bpy.context.object
        pivot.name = "CharPivot"
        bpy.context.view_layer.update()
        roots = [o for o in bpy.data.objects if o.parent is None and o != pivot and o.users_collection]
        for root in roots:
            root.parent = pivot
            root.matrix_parent_inverse = pivot.matrix_world.inverted()
        pivot.scale = (s, s, s)
        pivot.location = (0.0, 0.0, 0.0)
        bpy.context.view_layer.update()
        print("ASTRID_NORMALIZED scale=" + repr(s))
    except Exception as exc:  # noqa: BLE001
        print("ASTRID_NORMALIZE_FAIL=" + str(exc))
        bpy.ops.object.empty_add(location=(0, 0, 0))
        pivot = bpy.context.object
        pivot.name = "CharPivot"

    FRAMES = int(SETTINGS.get("frames", 60))
    turn_end = max(8, int(FRAMES * 0.45))
    head_yaw_deg = float(SETTINGS.get("head_yaw_deg", 155))
    body_yaw_deg = float(SETTINGS.get("body_yaw_deg", 0))

    # Body stays static (back to camera). Optional flip if the model's front
    # initially faces the camera (set body_yaw_deg=180).
    pivot.rotation_euler = (0, 0, math.radians(body_yaw_deg))

    # Stop any imported walk/idle animation so the figure holds a static pose.
    try:
        for o in list(bpy.data.objects):
            if o.animation_data is not None:
                o.animation_data_clear()
    except Exception as exc:  # noqa: BLE001
        print("ASTRID_ANIM_CLEAR_FAIL=" + str(exc))

    armature = next((o for o in bpy.data.objects if o.type == "ARMATURE"), None)
    low = {b.name: b.name.lower() for b in (armature.pose.bones if armature else [])}

    # --- ARMS by the sides: drop each upper-arm bone straight down (static) ---
    if armature is not None:
        def _drop_bone(pname, target):
            try:
                pb2 = armature.pose.bones[pname]
                m = pb2.matrix.copy()
                R = m.to_3x3()
                curY = R.col[1].normalized()
                q = curY.rotation_difference(target)
                newR = q.to_matrix() @ R
                pb2.matrix = Matrix.Translation(m.translation) @ newR.to_4x4()
                return True
            except Exception as exc:  # noqa: BLE001
                print("ASTRID_ARM_FAIL=" + pname + ": " + str(exc))
                return False
        arm_bones = [b.name for b in armature.pose.bones if "arm" in low[b.name] and "forearm" not in low[b.name]]
        down = Vector((0.0, 0.0, -1.0))
        for side in ("left", "right"):
            side_bones = [n for n in arm_bones if side in low[n]]
            if side_bones:
                canon = min(side_bones, key=len)
                if _drop_bone(canon, down):
                    print("ASTRID_ARM_DOWN=" + canon)

    # --- HEAD turn only (like someone called their name) ---
    head_bone = None
    if armature is not None:
        cand = [b.name for b in armature.pose.bones
                if "head" in low[b.name] and not any(x in low[b.name] for x in ("top", "end", "tip"))]
        if not cand:
            cand = [b.name for b in armature.pose.bones if "neck" in low[b.name]]
        if cand:
            head_bone = min(cand, key=len)
    if head_bone is not None and armature is not None:
        pb = armature.pose.bones[head_bone]
        pb.rotation_mode = "XYZ"
        pb.rotation_euler = (0.0, 0.0, 0.0)
        pb.keyframe_insert(data_path="rotation_euler", frame=1)
        pb.rotation_euler = (0.0, math.radians(head_yaw_deg), 0.0)
        pb.keyframe_insert(data_path="rotation_euler", frame=turn_end)
        print("ASTRID_HEAD_TURN=" + head_bone + " yaw=" + str(head_yaw_deg))
    else:
        print("ASTRID_HEAD_TURN=none (no head/neck bone found)")

    # --- WINK: drive a right-eye blink shape key right after the head turn ---
    wink_done = False
    try:
        candidates = []
        for m in meshes:
            sk = getattr(m.data, "shape_keys", None)
            if not sk:
                continue
            for name, kb in sk.key_blocks.items():
                lo = name.lower()
                if any(k in lo for k in ("blink", "wink", "eyeclose", "eye_close", "closeeye", "eyesquint")):
                    is_right = ("right" in lo) or lo.endswith("r") or ("_r" in lo) or ("righteye" in lo)
                    candidates.append((0 if is_right else 1, lo, m, kb))
        if candidates:
            candidates.sort()
            _, _, mesh, kb = candidates[0]
            wc = turn_end + max(3, int(FRAMES * 0.08))
            wo = wc + max(3, int(FRAMES * 0.08))
            kb.value = 0.0; kb.keyframe_insert(data_path="value", frame=max(1, wc - 4))
            kb.value = 1.0; kb.keyframe_insert(data_path="value", frame=wc)
            kb.value = 0.0; kb.keyframe_insert(data_path="value", frame=wo)
            kb.value = 0.0; kb.keyframe_insert(data_path="value", frame=FRAMES)
            wink_done = True
            print("ASTRID_WINK=" + kb.name)
    except Exception as exc:  # noqa: BLE001
        print("ASTRID_WINK_FAIL=" + str(exc))
    if not wink_done:
        print("ASTRID_WINK=none (no eye shape key on this rig)")

    # --- camera dolly-zoom onto the head (head stays put; only rotates) ---
    bpy.ops.object.empty_add(location=(0, 0, 1.72))
    head_target = bpy.context.object
    head_target.name = "HeadTarget"
    bpy.ops.object.camera_add(location=(0, -5.5, 1.7))
    cam = bpy.context.object
    sce.camera = cam
    trk = cam.constraints.new(type="TRACK_TO")
    trk.target = head_target
    trk.track_axis = "TRACK_NEGATIVE_Z"
    trk.up_axis = "UP_Y"
    cam.data.lens = 50
    cam.location = (0, -5.5, 1.72); cam.keyframe_insert(data_path="location", frame=1)
    cam.location = (0, -2.7, 1.70); cam.keyframe_insert(data_path="location", frame=turn_end)
    cam.location = (0, -1.0, 1.73); cam.keyframe_insert(data_path="location", frame=FRAMES)

    # --- lights + world ---
    bpy.ops.object.light_add(type="AREA", location=(4, -4, 5))
    a = bpy.context.object; a.data.energy = 900; a.data.size = 4
    a.rotation_euler = (math.radians(60), 0, math.radians(35))
    bpy.ops.object.light_add(type="SUN", location=(0, 0, 8))
    bpy.context.object.data.energy = 2.5
    world = bpy.data.worlds.new("AstridWorld")
    sce.world = world
    world.use_nodes = True
    bg = world.node_tree.nodes.get("Background")
    if bg is not None:
        bg.inputs["Color"].default_value = (0.07, 0.08, 0.11, 1.0)
        bg.inputs["Strength"].default_value = 1.0

    # --- render settings + animation ---
    res = SETTINGS.get("resolution", [640, 480])
    sce.render.resolution_x = int(res[0])
    sce.render.resolution_y = int(res[1])
    sce.render.resolution_percentage = 100
    sce.render.fps = int(SETTINGS.get("fps", 24))
    engine = SETTINGS.get("engine", "cycles")
    if engine == "cycles":
        sce.render.engine = "CYCLES"
        sce.cycles.device = SETTINGS.get("device", "CPU").upper()
        sce.cycles.samples = int(SETTINGS.get("samples", 32))
        sce.cycles.use_denoising = bool(SETTINGS.get("denoise", False))
    sce.render.image_settings.file_format = "PNG"
    sce.render.image_settings.color_mode = "RGBA"
    sce.frame_start = 1
    sce.frame_end = FRAMES
    os.makedirs(OUTPUT, exist_ok=True)
    sce.render.filepath = os.path.join(OUTPUT, "frame_")
    bpy.ops.render.render(animation=True, write_still=True)
    print("ASTRID_BLENDER_OUT=" + OUTPUT)


if __name__ == "__main__":
    build()
'''


def build(settings: dict[str, Any] | None) -> str:
    """Return a self-contained Blender script for the wink-turn render.

    ``__MESH_FILE__`` and ``__OUTPUT__`` are left as placeholders for the render
    runner to fill (the resolved mesh path and output directory).
    """
    norm = normalize_settings(settings)
    script = _TEMPLATE.replace("__SETTINGS__", repr(norm))
    return script
