// DO NOT EDIT — generated by tools/scripts/gen_remotion_types.py
//
// Naming convention: TypedDicts re-exported from
// banodoco_timeline_schema (AssetEntry, Theme, ThemeOverrides,
// TimelineClip, TimelineConfig, TimelineOutput) are emitted with the
// `Shared*` name as the canonical TS interface. The un-prefixed name
// (plus any other in-repo alias such as AssetRegistryEntry) is emitted
// as `export type X = SharedX;` for back-compat. New code should
// prefer the `Shared*` name.

export type AnimationReferenceList =
  | string
  | AnimationReferenceObject
  | (string | AnimationReferenceObject)[];

export interface AnimationReferenceObject {
  durationFrames?: number;
  easing?: string;
  id?: string;
  params?: Record<string, unknown>;
}

export interface Arrangement {
  brief_sha256?: string;
  brief_slug?: string;
  brief_text?: string;
  clips?: ArrangementClip[];
  generated_at?: string;
  pool_sha256?: string;
  source_slug?: string;
  target_duration_sec?: number;
  version?: number;
}

export interface ArrangementAudioSource {
  pool_id: string;
  trim_sub_range: number[];
}

export interface ArrangementClip {
  audio_source: ArrangementAudioSource | null;
  order: number;
  rationale: string;
  text_overlay?: ArrangementTextOverlay | null;
  uuid: string;
  visual_source: ArrangementVisualSource;
}

export interface ArrangementTextOverlay {
  content?: string;
  style_preset?: string;
}

export interface ArrangementVisualSource {
  params?: Record<string, unknown>;
  pool_id: string;
  role: 'overlay' | 'primary' | 'stinger';
}

export interface AssetRegistry {
  assets: Record<string, SharedAssetEntry>;
}

export interface AudioBindingValue {
  max: number;
  min: number;
  source: 'amplitude' | 'bass' | 'mid' | 'treble';
}

export interface ClipContinuous {
  intensity?: number;
  params?: Record<string, unknown>;
  type?: string;
}

export interface ClipEntrance {
  duration?: number;
  intensity?: number;
  params?: Record<string, unknown>;
  type?: string;
}

export interface ClipExit {
  duration?: number;
  intensity?: number;
  params?: Record<string, unknown>;
  type?: string;
}

export interface ClipTransition {
  duration: number;
  type: string;
}

export interface ClipTransitionReference {
  duration?: number;
  durationFrames?: number;
  id?: string;
  params?: Record<string, unknown>;
  type?: string;
}

export interface ParameterDefinition {
  default?: unknown;
  description: string;
  label: string;
  max?: number;
  min?: number;
  name: string;
  options?: ParameterOption[];
  step?: number;
  type: 'audio-binding' | 'boolean' | 'color' | 'number' | 'select';
}

export interface ParameterOption {
  label: string;
  value: string;
}

export interface PipelineMetadata {
  clips: Record<string, PipelineMetadataClipEntry>;
  generated_at: string;
  pipeline: Record<string, unknown>;
  sources: Record<string, Record<string, unknown>>;
  version: number;
}

export interface PipelineMetadataClipEntry {
  arrangement_notes?: null | string;
  caption_kind?: 'dialogue' | 'visual';
  pick_rationale?: string;
  picked_by?: string;
  pool_id?: null | string;
  pool_kind?: 'applause' | 'dialogue' | 'music' | 'reaction' | 'text' | 'visual';
  score?: number;
  source_ids?: SourceIds;
  source_scene_id?: string;
  source_transcript_text?: null | string;
  source_uuid?: string;
  text_overlay_content?: string;
}

export interface Pool {
  entries?: PoolEntry[];
  generated_at?: string;
  source_slug?: string;
  version?: number;
}

export interface PoolEntry {
  asset?: string;
  bed_kind?: string;
  camera?: string;
  category: 'applause' | 'dialogue' | 'music' | 'reaction' | 'visual';
  defaults?: Record<string, unknown>;
  duration: number;
  effect_id?: string;
  energy?: number;
  event_label?: string;
  excluded: boolean;
  excluded_reason?: null | string;
  id: string;
  intensity?: number;
  kind: 'generative' | 'source';
  meta?: Record<string, unknown>;
  mood_tags?: string[];
  motion_tags?: string[];
  param_schema?: Record<string, unknown>;
  quote_kind?: string;
  scores: PoolScores;
  source_ids?: SourceIds;
  speaker?: null | string;
  src_end?: number;
  src_start?: number;
  subject?: string;
  text?: string;
}

export interface PoolScores {
  deep?: number;
  quotability?: number;
  triage?: number;
}

export interface SharedAssetEntry {
  content_sha256?: string;
  duration?: number;
  etag?: string;
  file?: string;
  fps?: number;
  generationId?: string;
  resolution?: string;
  type?: string;
  url?: string;
  url_expires_at?: string;
}

export type AssetEntry = SharedAssetEntry;

export type AssetRegistryEntry = SharedAssetEntry;

export interface SharedTheme {
  audio?: Record<string, unknown>;
  generation?: Record<string, unknown>;
  pacing?: Record<string, unknown>;
  visual?: Record<string, unknown>;
  voice?: Record<string, unknown>;
}

export type Theme = SharedTheme;

export interface SharedThemeOverrides {
  audio?: Record<string, unknown>;
  generation?: Record<string, unknown>;
  pacing?: Record<string, unknown>;
  visual?: Record<string, unknown>;
  voice?: Record<string, unknown>;
}

export type ThemeOverrides = SharedThemeOverrides;

export interface SharedTimelineClip {
  asset?: string;
  at?: number;
  clipType?: string;
  clip_order?: number;
  continuous?: AnimationReferenceList;
  cropBottom?: number;
  cropLeft?: number;
  cropRight?: number;
  cropTop?: number;
  effects?: TimelineEffect[] | Record<string, number>;
  entrance?: AnimationReferenceList;
  exit?: AnimationReferenceList;
  from?: number;
  generation?: Record<string, unknown>;
  height?: number;
  hold?: number;
  id?: string;
  opacity?: number;
  params?: Record<string, unknown>;
  pool_id?: string;
  source_uuid?: string;
  speed?: number;
  text?: TextClipData;
  to?: number;
  track?: string;
  transition?: ClipTransitionReference | string;
  volume?: number;
  width?: number;
  x?: number;
  y?: number;
}

export type TimelineClip = SharedTimelineClip;

export type Clip = SharedTimelineClip;

export interface SharedTimelineConfig {
  clips?: SharedTimelineClip[];
  generation_defaults?: Record<string, unknown>;
  output?: SharedTimelineOutput;
  pinnedShotGroups?: Record<string, unknown>[];
  theme?: string;
  theme_overrides?: SharedThemeOverrides;
  tracks?: TrackDefinition[];
}

export type TimelineConfig = SharedTimelineConfig;

export interface SharedTimelineOutput {
  background?: string;
  background_scale?: number;
  file?: string;
  fps?: number;
  resolution?: string;
}

export type TimelineOutput = SharedTimelineOutput;

export interface SourceIds {
  scene_id?: string;
  segment_ids?: number[];
}

export interface TextClipData {
  align?: 'center' | 'left' | 'right';
  bold?: boolean;
  color?: string;
  content?: string;
  fontFamily?: string;
  fontSize?: number;
  italic?: boolean;
}

export interface TimelineEffect {
  fade_in?: number;
  fade_out?: number;
}

export interface TrackDefinition {
  blendMode?: 'darken' | 'hard-light' | 'lighten' | 'multiply' | 'normal' | 'overlay' | 'screen' | 'soft-light';
  fit?: 'contain' | 'cover' | 'manual';
  id: string;
  kind: 'audio' | 'visual';
  label: string;
  muted?: boolean;
  opacity?: number;
  scale?: number;
  volume?: number;
}

export const _ASSET_ENTRY_ALLOWED = ['content_sha256', 'duration', 'etag', 'file', 'fps', 'generationId', 'resolution', 'thumbnailUrl', 'type', 'url', 'url_expires_at', 'variantId'] as const;
export const _CLIP_ALLOWED = ['asset', 'at', 'clipType', 'clip_order', 'continuous', 'cropBottom', 'cropLeft', 'cropRight', 'cropTop', 'effects', 'entrance', 'exit', 'from', 'generation', 'height', 'hold', 'id', 'opacity', 'params', 'pool_id', 'source_uuid', 'speed', 'text', 'to', 'track', 'transition', 'volume', 'width', 'x', 'y'] as const;
export const _THEME_OVERRIDES_ALLOWED = ['audio', 'generation', 'pacing', 'visual', 'voice'] as const;
export const _TIMELINE_TOP_ALLOWED = ['clips', 'generation_defaults', 'output', 'pinnedShotGroups', 'theme', 'theme_overrides', 'tracks'] as const;
export const _TRACK_ALLOWED = ['blendMode', 'fit', 'id', 'kind', 'label', 'muted', 'opacity', 'scale', 'volume'] as const;
