// DO NOT EDIT - generated by tools/scripts/gen_effect_registry.py
import type {EffectComponent} from './effects-types';
import ArtCard from '@theme-effects/art-card/component';
import CtaCard from '@theme-effects/cta-card/component';
import ResourceCard from '@theme-effects/resource-card/component';
import SectionHook from '@theme-effects/section-hook/component';
import TextCard from '@workspace-effects/text-card/component';

export const ACTIVE_THEME_ID = "2rp" as const;
export const EFFECT_IDS = ['art-card', 'cta-card', 'resource-card', 'section-hook', 'text-card'] as const;
export type EffectId = typeof EFFECT_IDS[number];
export const EFFECT_REGISTRY: Record<EffectId, EffectComponent> = {
  'art-card': ArtCard,
  'cta-card': CtaCard,
  'resource-card': ResourceCard,
  'section-hook': SectionHook,
  'text-card': TextCard,
};
export const CLIP_TYPE_ALIASES: Record<string, EffectId> = {
  text: 'text-card',
};
