"""Shared Astrid schema contracts used across executors and orchestrators."""

from .artifact_types import (
    ARTIFACT_TYPE_REGISTRY,
    ArtifactTypeDescriptor,
    ArtifactTypeRegistry,
    ArtifactTypeRegistryError,
)
from .errors import (
    AstridError,
    AstridErrorEnvelope,
    build_state_snapshot,
    coerce_astrid_error,
    error_from_result,
    normalize_valid_options,
    render_astrid_error,
    wrap_degraded_error,
)
from .schema import (
    CACHE_MODES,
    ISOLATION_MODES,
    OUTPUT_MODES,
    PORT_REQUIRED_TYPES,
    AliasRecord,
    CachePolicy,
    CapabilityHandle,
    CommandSpec,
    IsolationMetadata,
    Output,
    Port,
    Provenance,
    SafetyDeclaration,
)
from .scoped_config import (
    SCOPE_REGISTRY,
    ScopedConfig,
    ScopeKey,
    ScopeRegistry,
    ScopeRequest,
)

__all__ = [
    "ARTIFACT_TYPE_REGISTRY",
    "ArtifactTypeDescriptor",
    "ArtifactTypeRegistry",
    "ArtifactTypeRegistryError",
    "CACHE_MODES",
    "ISOLATION_MODES",
    "OUTPUT_MODES",
    "PORT_REQUIRED_TYPES",
    "AstridError",
    "AstridErrorEnvelope",
    "AliasRecord",
    "build_state_snapshot",
    "CachePolicy",
    "CapabilityHandle",
    "CommandSpec",
    "coerce_astrid_error",
    "error_from_result",
    "IsolationMetadata",
    "normalize_valid_options",
    "Output",
    "Port",
    "Provenance",
    "render_astrid_error",
    "SCOPE_REGISTRY",
    "SafetyDeclaration",
    "ScopeKey",
    "ScopeRegistry",
    "ScopeRequest",
    "ScopedConfig",
    "wrap_degraded_error",
]
